#	Lupinia Studios
#	By Natasha L.
#	www.lupinia.net | github.com/lupinia
#	
#	=================
#	General utility functions/objects
#	=================

import platform

from django.conf import settings
from django.contrib.sites.models import Site
from django.core.mail import mail_admins, send_mail

#	Notification generator
def notify(subject, msg, recipients=None):
	admin_message = {}
	message = {}
	admin_message_status = False
	message_status = False
	
	cur_site_check = Site.objects.filter(pk=settings.SITE_ID)
	if cur_site_check.exists():
		cur_site = cur_site_check.first()
		cur_site_url = cur_site.domain
	else:
		cur_site_url = platform.node()
	msg_text = """%s 

=============
Message generated by %s.""" % (msg, cur_site_url)
	
	admin_message['message'] = msg_text
	admin_message['subject'] = subject
	
	if recipients:
		message['subject'] = '%s%s' % (settings.EMAIL_SUBJECT_PREFIX, subject)
		message['message'] = msg_text
		message['recipient_list'] = recipients
		message['from_email'] = settings.DEFAULT_FROM_EMAIL
		message_status = send_mail(**message)
		
		admin_message['subject'] = '%s (Admin CC)' % subject
	else:
		message_status = True
	
	admin_message_status = mail_admins(**admin_message)
	
	if admin_message_status and message_status:
		return True
	else:
		return False
